name: frank_mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  another_flutter_splash_screen: ^1.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.4
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  get_it: ^7.6.4
  go_router: ^12.1.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
